refinedarchitectVersion=1.6.4
refinedstorageVersion=3.2.0
refinedstorageQuartzArsenalVersion=2.0.6
jeiVersion=29.5.0.24
minecraftVersion=26.1.2
# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
