modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorage-jei-integration"
license = "MIT"
[[mods]]
modId = "refinedstorage_jei_integration"
version = "${version}"
displayName = "Refined Storage - JEI Integration"
displayURL = "https://refinedmods.com/refined-storage"
authors = "Refined Mods"
description = '''
JEI integration for Refined Storage.
'''
[[dependencies.refinedstorage_jei_integration]]
modId = "refinedstorage"
type = "required"
versionRange = "2.0.0-milestone.4.8"
side = "BOTH"
[[dependencies.refinedstorage_jei_integration]]
modId = "jei"
type = "required"
versionRange = "[19.20.0,)"
side = "BOTH"
