name: Publish release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  publish-release:
    uses: refinedmods/refinedarchitect/.github/workflows/publish-release.yml@v0.13.4
    secrets: inherit
    with:
      project-name: 'Refined Storage - JEI Integration'
      mutation-testing: false
      javadoc: false